<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \Application\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'identificador', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'inicio', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'fim', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'cargaHoraria', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'maximoParticipantes', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'preco', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'tipo', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'local', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'monitor', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'palestrante', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'inscritos', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'cadastradoEm'];
        }

        return ['__isInitialized__', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'identificador', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'inicio', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'fim', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'cargaHoraria', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'maximoParticipantes', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'preco', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'tipo', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'local', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'monitor', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'palestrante', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'inscritos', '' . "\0" . 'Application\\Entity\\Evento' . "\0" . 'cadastradoEm'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentificador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentificador', []);

        return parent::getIdentificador();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentificador($identificador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentificador', [$identificador]);

        return parent::setIdentificador($identificador);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInicio', []);

        return parent::getInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setInicio($inicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInicio', [$inicio]);

        return parent::setInicio($inicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFim', []);

        return parent::getFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setFim($fim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFim', [$fim]);

        return parent::setFim($fim);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargaHoraria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargaHoraria', []);

        return parent::getCargaHoraria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargaHoraria($cargaHoraria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargaHoraria', [$cargaHoraria]);

        return parent::setCargaHoraria($cargaHoraria);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaximoParticipantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaximoParticipantes', []);

        return parent::getMaximoParticipantes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaximoParticipantes($maximoParticipantes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaximoParticipantes', [$maximoParticipantes]);

        return parent::setMaximoParticipantes($maximoParticipantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreco', []);

        return parent::getPreco();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreco($preco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreco', [$preco]);

        return parent::setPreco($preco);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal', []);

        return parent::getLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal($local)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal', [$local]);

        return parent::setLocal($local);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonitor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonitor', []);

        return parent::getMonitor();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonitor($monitor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonitor', [$monitor]);

        return parent::setMonitor($monitor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPalestrante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPalestrante', []);

        return parent::getPalestrante();
    }

    /**
     * {@inheritDoc}
     */
    public function setPalestrante($palestrante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPalestrante', [$palestrante]);

        return parent::setPalestrante($palestrante);
    }

    /**
     * {@inheritDoc}
     */
    public function addPalestrante($palestrante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPalestrante', [$palestrante]);

        return parent::addPalestrante($palestrante);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscritos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscritos', []);

        return parent::getInscritos();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscritos($inscritos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscritos', [$inscritos]);

        return parent::setInscritos($inscritos);
    }

    /**
     * {@inheritDoc}
     */
    public function addInscritos($inscrito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInscritos', [$inscrito]);

        return parent::addInscritos($inscrito);
    }

    /**
     * {@inheritDoc}
     */
    public function getCadastradoEm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCadastradoEm', []);

        return parent::getCadastradoEm();
    }

    /**
     * {@inheritDoc}
     */
    public function setCadastradoEm($cadastradoEm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCadastradoEm', [$cadastradoEm]);

        return parent::setCadastradoEm($cadastradoEm);
    }

}
