<?php
namespace Application\Service;

use Base\Service\AbstractService;
use Doctrine\ORM\EntityManager;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;
use Zend\Filter\Exception\InvalidArgumentException;
use Zend\Stdlib\Hydrator;


class Participante extends AbstractService{

    public function __construct(EntityManager $em){
        parent::__construct($em);

        $this->entity = 'Application\Entity\Participante';
        $this->errorCodeValidator[1062] = 'O cpf informado nesse cadastro já foi utilizado em ouro cadastro';
    }

    public function update($data)
    {
        if(empty($data['senha'])){
            unset($data['senha']);
            unset($data['confirmarsenha']);
        }

        return parent::update($data); // TODO: Change the autogenerated stub
    }
}

