<?php
/** @var  $entity \Application\Entity\Evento */
$entity= $this->entity;
?>

<div class="row">
    <div class="col-md-12">
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit portlet-datatable">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-calendar font-green"></i>
                    <span class="caption-subject font-green sbold uppercase">
                        <?php echo $entity->getTitulo(); ?>
                    </span>
                </div>
            </div>
            <div>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="portlet light bg-inverse">
                            <div class="portlet-body ">
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Local: </div>
                                    <div class="col-md-7 value"> <?php echo $entity->getLocal(); ?> </div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Início: </div>
                                    <div class="col-md-7 value"> <?php echo $entity->getInicio()->format('d/m/y h:i'); ?> </div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Encerramento: </div>
                                    <div class="col-md-7 value"> <?php echo $entity->getFim()->format('d/m/y h:i'); ?> </div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Tipo: </div>
                                    <div class="col-md-7 value"> <?php echo $entity->getTipo() ?> </div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Preço: </div>
                                    <div class="col-md-7 value"> <?php echo $this->currencyFormat($entity->getPreco(), 'BRL', true, 'pt_BR', 'R$ #0.#');?> </div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Máximo de participantes : </div>
                                    <div class="col-md-7 value"> <?php echo $entity->getMaximoParticipantes() ?> </div>
                                </div>
                                <div class="row static-info">
                                    <div class="col-md-5 name"> Carga horária: </div>
                                    <div class="col-md-7 value"> <?php echo $entity->getCargaHoraria(); ?> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    <div class="portlet light">
                                        <div class="portlet-title">
                                            <div class="caption">
                                                Inscritos
                                            </div>
                                        </div>
                                        <div class="portlet-body">
                                            <div class="table-responsive">
                                                <table class="table table-hover table-bordered table-striped">
                                                    <thead>
                                                    <tr>
                                                        <th> Participante</th>
                                                        <th> Status </th>
                                                        <th> Data da inscrição </th>
                                                        <th>  </th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    <?php
                                                    /** @var  $inscricao  \Application\Entity\Inscricao*/
                                                    foreach ($entity->getInscritos() as $inscricao):?>
                                                        <tr>
                                                            <td> <?php echo $inscricao->getParticipante(); ?> </td>
                                                            <td> <?php echo $inscricao->getStatus(); ?> </td>
                                                            <td> <?php echo $inscricao->getData()->format('d/m/Y h:i'); ?> </td>

                                                        </tr>
                                                    <?php endforeach; ?>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
