<?php
/** @var  $row \Application\Entity\Evento */
$data = $this->data;
?>


<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-calendar font-green"></i>
            <span class="caption-subject font-green bold uppercase"> Eventos</span>
            <span class="caption-helper"></span>
        </div>
        <div class="actions">
            <a href="<?php echo $this->url('evento/default', array('action' => 'cadastrar'))?>" class="btn green ">
                <i class="fa fa-plus" style="padding-right: 5px"></i> Novo
            </a>

            <a class="btn  btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>

        <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_1">
            <thead>
            <tr>
                <th class="all">Identificador</th>
                <th>Título</th>
                <th>Data</th>
                <th  class="none">Palestrante</th>
                <th class="none">Max. Participantes</th>
                <th  class="none">Local</th>
                <th  class="none">Preço</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($data as $row): ?>
                <tr>
                    <td><?php echo $row->getIdentificador(); ?></td>
                    <td><?php echo $row->getTitulo(); ?></td>
                    <td>
                        <?php echo $row->getInicio()->format('d/m/y h:i'); ?> até
                        <?php echo $row->getFim()->format('h:i'); ?>
                    </td>
                    <td>
                        <?php foreach ($row->getPalestrante() as $palestrante): ?>
                            <?php echo $palestrante->getDescricao(); ?>
                        <?php endforeach; ?>
                    </td>
                    <td><?php echo $row->getMaximoParticipantes(); ?></td>
                    <td><?php echo $row->getLocal(); ?></td>
                    <td><?php echo $row->getPreco(); ?></td>


                    <td style=" text-align: right;">
                        <div class="clearfix">
                            <a href="<?php  echo $this->url('evento/default', array('action' => 'editar', 'id' => $row->getId()));?>" class="btn btn-icon-only yellow-saffron" title="Editar">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>

                            <a href="<?php  echo $this->url('evento/default', array('action' => 'detalhes', 'id' => $row->getId()));?>" class="btn btn-icon-only blue-sharp" title="Detalhes para <?php echo$row->getTitulo();  ?>">
                                <i class="fa fa-info" aria-hidden="true"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>


