<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8" />
</head>
<body>
    <div style="text-align: center; font-weight: bold;">Átomo Co-work ICMS - SUPORTE</div>
    <h3 style="color: #000; font-size: 15px;"> Assunto:  <?php echo $this->data['assunto']; ?></h3>
    <h3 style="color: #000; font-size: 15px;"> Descrição</h3>
    <p><?php echo $this->data['descricao']; ?></p>
    <h3 style="color: #000; font-size: 15px;"> Texto do erro (opcional)</h3>
    <p><?php echo $this->data['erro']; ?></p>
</body>
</html>
