<table cellspacing="0" cellpadding="0" border="0">
    <tbody>
    <tr>
        <td style="padding:15px 15px 0 15px;background:#fff;border-radius:4px 4px 0 0">
            <div>
                <img src="http://itp.infinitescript.com/img/logo.png" alt="IT Training Platform" height="85" width="290">
            </div>
        </td>
    </tr>
    <tr>
        <td style="padding:15px; background:#fff; border-radius:0 0 4px 4px;font-size:12px">
            We received a request to reset the password for your account, <?=$this->username?>.<br><br>
            If you made this request, click the link below. If you didn't make this request, you can ignore this email.<br><br>
            <a href="http://itp.infinitescript.com/accounts/resetPassword?email=<?=$this->email?>&keycode=<?=$this->keycode?>" target="_blank"style="color: #005399;text-decoration: none;">http://itp.infinitescript.com/accounts/resetPassword?email=<?=$this->email?>&keycode=<?=$this->keycode?></a><br><br>
            Yours, <br>
            IT Training Platform.<br><br>
            <div style="border-top:3px solid #eee;color:#999;font-size:11px;line-height:1.2">
                <br>Powered by <a href="http://itp.infinitescript.com" target="_blank" style="color: #005399;text-decoration: none;">IT Training Platform</a>. All rights reserved.<br>
            </div>
        </td>
    </tr>
    </tbody>
</table>