<?php
/** @var  $row \Application\Entity\Inscricao */
$data = $this->data;
?>


<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-list-alt font-green"></i>
            <span class="caption-subject font-green bold uppercase"> Inscrições</span>
            <span class="caption-helper"></span>
        </div>
        <div class="actions">
            <a href="<?php echo $this->url('inscricao/default', array('action' => 'cadastrar'))?>" class="btn green ">
                <i class="fa fa-plus" style="padding-right: 5px"></i> Novo
            </a>

            <a class="btn  btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>

        <table class="table table-striped table-bordered table-hover dt-responsive" width="100%" id="sample_1">
            <thead>
            <tr>
                <th class="all">Participante</th>
                <th>Evento</th>
                <th>Preço</th>
                <th>Status</th>
                <th title="Altere o status a incrição clicando em uma das opções abaixo.">Aterar</th>
                <th class="none">CPF </th>
                <th class="none">Inscrição feita em </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($data as $row): ?>
                <tr>
                    <td><?php echo $row->getParticipante(); ?></td>
                    <td><?php echo $row->getEvento(); ?></td>
                    <td><?php echo $this->currencyFormat($row->getEvento()->getPreco(), 'BRL', true, 'pt_BR', 'R$ #0.#');?></td>
                    <td>
                        <span class="label <?php echo $row->getStatus(); ?>">  <?php echo $row->getStatus(); ?> </span>
                    </td>
                    <td style="width: 80px;">
                        <div class="clearfix">

                            <?php if($row->getStatus() != 'pago'): ?>
                                <a href="<?php  echo $this->url('inscricao/default', array('action' => 'pagar', 'evento' => $row->getEvento()->getId(), 'id' => $row->getId()));?>" class="btn btn-icon-only green" title="Alterar status da inscrição para pago">
                                    <i class="fa fa-money" aria-hidden="true"></i>
                                </a>
                            <?php endif; ?>

                            <?php if($row->getStatus() != 'cancelado'): ?>
                                <a href="<?php  echo $this->url('inscricao/default', array('action' => 'cancelar', 'evento' => $row->getEvento()->getId(), 'id' => $row->getId()));?>" class="btn  btn-icon-only red" title="Altere o status da inscrição para cancelado">
                                    <i class="fa fa-close" aria-hidden="true"></i>
                                </a>
                            <?php endif; ?>

                            <?php if($row->getStatus() != 'andamento'): ?>
                                <a href="<?php  echo $this->url('inscricao/default', array('action' => 'andamento', 'evento' => $row->getEvento()->getId(), 'id' => $row->getId()));?>" class="btn  btn-icon-only grey-mint" title="Restaurar inscrição para o estado 'Em andamento'">
                                    <i class="fa fa-refresh" aria-hidden="true"></i>
                                </a>
                            <?php endif; ?>

                        </div>
                    </td>
                    <td><?php echo $row->getParticipante()->getCpf(); ?></td>
                    <td><?php echo $row->getData()->format('d/m/Y h:i'); ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<script type="text/javascript">
    $()
</script>

