<div class="navbar-custom-menu">
    <ul class="nav navbar-nav">
        <!-- Messages: style can be found in dropdown.less-->
       <?php //echo $this->partial('partial/main-header/navbar-custom-menu/messages-menu'); ?>
        <!-- Notifications: style can be found in dropdown.less -->
        <?php //echo $this->partial('partial/main-header/navbar-custom-menu/notifications-menu'); ?>
        <!-- Tasks: style can be found in dropdown.less -->
        <?php //echo $this->partial('partial/main-header/navbar-custom-menu/tasks-menu'); ?>
        <!-- User Account: style can be found in dropdown.less -->
        <?php echo $this->partial('partial/main-header/navbar-custom-menu/user-menu'); ?>
        <!-- Control Sidebar Toggle Button -->
        <?php //echo $this->partial('partial/main-header/navbar-custom-menu/control-sidebar'); ?>

    </ul>
</div>