<div class="alert alert-warning alert-bold-border square fade in alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <strong> <?php echo $row; ?> não pode ser deletado</strong>  pois ele é utilizado em outros registros
    <br/><a href="<?php echo $this->url($this->rote, array('action' => 'listar')); ?>" class="alert-link">Voltar</a>
</div>


<?php if(!empty($references)):?>
<div class="the-box no-border alert alert-warning alert-bold-border square fade in alert-dismissable tiles-information">
    <div class="tiles-inner ">
        <h3>Os seguintes registros dependem de <?php echo$row; ?></h3>
        <br/>
        <ul class="list-unstyled">
            <?php foreach($references as $reference):?>
                <?php foreach($reference as $entity):?>
                    <li class="panel-footer">
                        <b><?php echo $entity->getNomeSingular()?></b>:
                        <span class="text-danger"><?php echo $entity->__toString()?></span>
                    </li>
                <?php endforeach; ?>
            <?php endforeach; ?>

        </ul>
        <br/>
    </div>
</div>
<?php endif; ?>

