<?php
/** @var  $usuario Application\Entity\Usuario*/
$container = new \Zend\Session\Container('logado');
$usuario    = $container->offsetGet('usuario');


?>

<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="/img/perfil.jpg" class="user-image" alt="User Image">
        <span class="hidden-xs"><?php echo $usuario['nome'];?></span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
            <img src="/img/perfil.jpg" class="img-circle" alt="User Image">
            <p>
                <?php echo $usuario['nome']; ?>
                <small><?php echo $usuario['tipo']; ?></small>
            </p>
        </li>
        <!-- Menu Body -->
        <!--
        <li class="user-body">
            <div class="col-xs-4 text-center">
                <a href="#">Seguidores</a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="#">Vendas</a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="#">Amigos</a>
            </div>
        </li>-->
        <!-- Menu Footer-->
        <li class="user-footer">
            <div class="pull-left">
                <?php if(!is_null($usuario)):?>
                <a href="<?php echo $this->url($usuario['tipo'].'/default', array('action' => 'perfil'))?>" class="btn btn-default btn-flat">Perfil</a>
                <?php endif; ?>
            </div>
            <div class="pull-right">
                <a href="<?php echo $this->url('logout')?>" class="btn btn-default btn-flat">Sair</a>
            </div>
        </li>
    </ul>
</li>