<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manutenção</title>
</head>
<body style="background: #ded7ff">

<div style="background: #eaf5ba; padding: 30px 20px; margin: 10% 20%; border: 1px solid #dadd98; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif">
    <h2 style="text-align: center;">AVISO</h2>

    <div style="text-align: center; font-size: 20px; padding-bottom: 30px;">
    Informamos que o sistema está em manutenção estamos providenciando as melhorias necessárias.
    </div>

</div

</body>
</html>