<?php
/** @var  $row \Application\Entity\Secao */
$data = $this->data;
?>

<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-users font-green"></i>
            <span class="caption-subject font-green bold uppercase"> perfil aluno </span>
            <span class="caption-helper"></span>
        </div>
        <div class="actions">
            <a class="btn  btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>
        <?php
        var_dump($this->aluno);
        ?>
    </div>
</div>
