<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">

            <li class="nav-item start ">
                <a href="<?php echo $this->url('evento/default', array('action' => 'listar'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-calendar"></i>
                    <span class="title">Eventos</span>
                </a>
            </li>

            <li class="nav-item start ">
                <a href="<?php echo $this->url('inscricao/default', array('action' => 'listar'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-list-alt" aria-hidden="true"></i>
                    <span class="title">Inscrições</span>
                </a>
            </li>

            <li class="nav-item start ">
                <a href="<?php echo $this->url('local/default', array('action' => 'listar'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <span class="title">Locais</span>
                </a>
            </li>

            <li class="nav-item start ">
                <a href="<?php echo $this->url('participante/default', array('action' => 'listar'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <span class="title">Participantes</span>
                </a>
            </li>


            <li class="nav-item start ">
                <a href="<?php echo $this->url('palestrante/default', array('action' => 'listar'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <span class="title">Palestrantes</span>
                </a>
            </li>


            <li class="heading">
                <h3 class="uppercase">Meu perfil</h3>
            </li>

            <li class="nav-item start ">
                <a href="<?php echo $this->url('perfil/default', array('action' => 'eventos'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-list-alt" aria-hidden="true"></i>
                    <span class="title">Minhas inscrições</span>
                </a>
            </li>


            <li class="heading">
                <h3 class="uppercase">CONTROLE DE ACESSO</h3>
            </li>

            <li class="nav-item  ">
                <a href="<?php echo $this->url('acl-privileges/default', array('action' => 'listar'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-key"></i>
                    <span class="title">Privilégios</span>
                </a>
            </li>

            <li class="nav-item  ">
                <a href="<?php echo $this->url('acl-resources/default', array('action' => 'listar'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-lock"></i>
                    <span class="title">Recursos</span>
                </a>
            </li>

            <li class="nav-item  ">
                <a href="<?php echo $this->url('acl-roles/default', array('action' => 'listar'))?>" class="nav-link nav-toggle">
                    <i class="fa fa-user"></i>
                    <span class="title">Papeis</span>
                </a>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>
