<?php /** @var $form \Zend\Form\Form */ ?>
<?php $form = $this->form; ?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
    <meta charset="utf-8" />
    <title>WeekIT - Semana de tecnologia da informação</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="/assets/global/plugins/typeahead/typeahead.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN THEME GLOBAL STYLES -->
    <link href="/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="/assets/global/css/plugins.min.css" rel="stylesheet" type="text/css" />
    <!-- END THEME GLOBAL STYLES -->
    <!-- END THEME LAYOUT STYLES -->
    <link rel="icon" type="image/png" href="/img/favicon.png" />
</head>
<!-- END HEAD -->

<body class="">

<div class="container">


     <img src="/assets/layouts/layout4/img/logo-cadastrar.png" alt="logo" class="logo-default img-responsive center-block"  style="margin: 20px auto; "/>


    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            <?php echo $this->partial('partial/messages');?>
            <?php $form->setAttribute('class', 'form-horizontal'); ?>
            <?php $form->prepare();
            ?>

            <?php echo $this->form()->openTag($form); ?>

            <div class="form-group">
                <div class="col-md-6  <?php if($this->formElementErrors($form->get('nome'))) echo " has-error" ?>">
                    <?php $form->get('sobrenome')->setAttribute('class', 'form-control '. $form->get('nome')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('nome')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('nome')
                    ))?>
                </div>

                <div class="col-md-6 <?php if($this->formElementErrors($form->get('sobrenome'))) echo " has-error" ?>">
                    <?php $form->get('sobrenome')->setAttribute('class', 'form-control '. $form->get('sobrenome')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('sobrenome')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('sobrenome')
                    ))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-3 <?php if($this->formElementErrors($form->get('cpf'))) echo " has-error" ?>">
                    <?php $form->get('cpf')->setAttribute('class', 'form-control '. $form->get('cpf')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('cpf')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('cpf')
                    ))?>
                </div>

                <div class="col-md-3 <?php if($this->formElementErrors($form->get('sexo'))) echo " has-error" ?>">
                    <?php $form->get('sexo')->setAttribute('class', 'form-control '. $form->get('sexo')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('sexo')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('sexo')
                    ))?>
                </div>

                <div class="col-md-3 <?php if($this->formElementErrors($form->get('telefone1'))) echo " has-error" ?>">
                    <?php $form->get('telefone1')->setAttribute('class', 'form-control '. $form->get('telefone1')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('telefone1')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('telefone1')
                    ))?>
                </div>

                <div class="col-md-3 <?php if($this->formElementErrors($form->get('telefone2'))) echo " has-error" ?>">
                    <?php $form->get('telefone2')->setAttribute('class', 'form-control '. $form->get('sexo')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('telefone2')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('telefone2')
                    ))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 <?php if($this->formElementErrors($form->get('instituicao'))) echo " has-error" ?>">
                    <?php $form->get('instituicao')->setAttribute('class', 'form-control '. $form->get('instituicao')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('instituicao')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('instituicao')
                    ))?>
                </div>
            </div>

            <div class="form-group">

                <div class="col-md-6 <?php if($this->formElementErrors($form->get('campus'))) echo " has-error" ?>">
                    <?php $form->get('campus')->setAttribute('class', 'form-control '. $form->get('campus')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('campus')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('campus')
                    ))?>
                </div>

                <div class="col-md-6 <?php if($this->formElementErrors($form->get('curso'))) echo " has-error" ?>">
                    <?php $form->get('curso')->setAttribute('class', 'form-control '. $form->get('curso')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('curso')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('curso')
                    ))?>
                </div>
            </div>

            <div class="form-group">

                <div class="col-md-12 <?php if($this->formElementErrors($form->get('email'))) echo " has-error" ?>">
                    <?php $form->get('email')->setAttribute('class', 'form-control '. $form->get('email')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('email')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('email')
                    ))?>
                </div>

            </div>

            <div class="form-group">
                <div class="col-md-12 <?php if($this->formElementErrors($form->get('senha'))) echo " has-error" ?>">
                    <?php $form->get('senha')->setAttribute('class', 'form-control '. $form->get('senha')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('senha')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('senha')
                    ))?>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 <?php if($this->formElementErrors($form->get('confirmarsenha'))) echo " has-error" ?>">
                    <?php $form->get('confirmarsenha')->setAttribute('class', 'form-control '. $form->get('confirmarsenha')->getAttribute('class')) ?>
                    <?php echo $this->formElement($form->get('confirmarsenha')); ?>
                    <?php echo $this->partial('partial/form/general/quick/message-erros', array(
                        'element' => $form->get('confirmarsenha')
                    ))?>
                </div>
            </div>

            <?php echo $this->formElement($form->get('csrf')); ?>
            <div class="col-md-12">
                <button type="submit" class="btn  green pull-right">Cadastrar</button>
            </div>


            </form>
        </div>
    </div>


</div>




<!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script>
<![endif]-->
<!-- BEGIN CORE PLUGINS -->
<script src="/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/js.cookie.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->

<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="/assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/typeahead/handlebars.min.js" type="text/javascript"></script>
<script src="/assets/global/plugins/typeahead/typeahead.bundle.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="/assets/global/scripts/app.min.js" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/pages/scripts/components-typeahead.js" type="text/javascript"></script>
<script src="/assets/pages/scripts/form-input-mask.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="/assets/layouts/layout4/scripts/layout.min.js" type="text/javascript"></script>
<script src="/assets/layouts/layout4/scripts/demo.min.js" type="text/javascript"></script>
<!-- END THEME LAYOUT SCRIPTS -->
</body>

</html>