<?php
/** @var  $row \Application\Entity\Participante */
$data = $this->data;
?>


<div class="portlet light">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-users font-green"></i>
            <span class="caption-subject font-green bold uppercase"> Participante</span>
            <span class="caption-helper"></span>
        </div>
        <div class="actions">
            <a href="<?php echo $this->url('participante/default', array('action' => 'cadastrar'))?>" class="btn green ">
                <i class="fa fa-plus" style="padding-right: 5px"></i> Novo
            </a>

            <a class="btn  btn-icon-only btn-default fullscreen" href="javascript:;" data-original-title="" title=""> </a>
        </div>
    </div>
    <div class="portlet-body" style="height: auto;">
        <?php echo $this->partial('partial/messages');?>

        <table class="table table-hover table-light" id="sample_1">
            <thead>
            <tr>
                <th>CPF</th>
                <th>Nome</th>
                <th>Telefone </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($data as $row): ?>
                <tr>
                    <td><?php echo $row->getCpf(); ?></td>
                    <td><?php echo $row->getNome() . ' '. $row->getSobrenome(); ?></td>
                    <td>
                        <?php echo $row->getTelefone1(); ?> <br/>
                        <?php echo $row->getTelefone2(); ?>
                    </td>
                    <td style=" text-align: center;">
                        <div class="clearfix">
                            <a href="<?php  echo $this->url('participante/default', array('action' => 'editar', 'id' => $row->getId()));?>" class="btn btn-icon-only yellow-saffron" title="Editar">
                                <i class="fa fa-pencil" aria-hidden="true"></i>
                            </a>

                            <a href="<?php  echo $this->url('participante/default', array('action' => 'editar', 'id' => $row->getId()));?>" class="btn btn-icon-only blue-sharp" title="Mais informações">
                                <i class="fa fa-info" aria-hidden="true"></i>
                            </a>
                        </div>

                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>


