<?php
/** @var  $element Zend\Form\Element\Email*/
$element = $this->element;
$col_1 =  ($this->col_1) ? $this->col_1 : 'col-md-3';
$col_2 =  ($this->col_2) ? $this->col_2 : 'col-md-6';
?>


<div class="form-group <?php if($this->formElementErrors($element)) echo " has-error" ?>">
    <label class="<?php echo $col_1;?> control-label">
        <?php echo $element->getLabel();?>
    </label>
    <div class="<?php echo $col_2;?>">
        <?php $element->setAttribute('class', 'form-control '. $element->getAttribute('class')) ?>
        <?php echo $this->formElement($element); ?>
        <?php echo $this->partial('partial/form/general/quick/message-erros', array(
            'element' => $element
        ))?>
    </div>
</div>
