<?php

/**
 * Esse partial éo hub para os outros partial de forms, redirecionando para form que definido no parametro,
 * caso oparametro não seja informado o partial utilizado para rederização será o 'general/quick'
 */

$form           = $this->form;
$type_form        = (is_null($this->type_form)) ? 'general/quick' : $this->type_form;
$col_1 =  ($this->col_1) ? $this->col_1 : 'col-md-3';
$col_2 =  ($this->col_2) ? $this->col_2 : 'col-md-6';

echo $this->partial('partial/form/'.$type_form, array(
    'form' => $form,
    'col_1' => $col_1,
    'col_2' => $col_2,
));



