<div class="box box-primary">
    <div class="box-header with-border">
        <i class="fa fa-map-marker" aria-hidden="true"></i>
        <h3 class="box-title">
            EDITAR ZONA
        </h3>
    </div>
    <div class="box-body">
        <!-- form start -->
        <?php
        echo $this->partial('partial/form/general/quick', array(
            'form' => $form,
            'edit' => true
        ));
        ?>
    </div>
</div>